post_bot: [TEMP] disable sending sticker
For some reason it breaks the poster

2022-01-08T19:05:43.8737220Z Traceback (most recent call last):
2022-01-08T19:05:43.8738135Z   File ".github/scripts/post.py", line 211, in <module>
2022-01-08T19:05:43.8738859Z     bot.send_sticker(CHAT_ID, STICKER_ID)
2022-01-08T19:05:43.8740341Z   File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 1253, in send_sticker
2022-01-08T19:05:43.8741198Z     apihelper.send_data(
2022-01-08T19:05:43.8742212Z TypeError: send_data() got an unexpected keyword argument 'protect_content'
2022-01-08T19:05:43.9024465Z ##[error]Process completed with exit code 1.